name: Continuous Integration

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Get the source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Check HTML file exists
      - name: Check HTML file
        run: |
          test -f shopping.html
          echo "HTML file found"


      # 4. Validate HTML
      - name: Validate HTML
        run: |
          grep -q "<html" shopping.html
          grep -q "</html>" shopping.html
          echo "HTML validation successful"


      # 6. CI completed
      - name: CI Success
        run: echo "Continuous Integration completed successfully"
